name: Issue workflow

on:
  issues:
    types: opened

  issue_comment: 
    types: created
jobs:
  print-issue-info:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show payload
        run: |
          echo '${{ toJson(github.event) }}'
      
      - name: Handle new issue
        if: github.event_name == 'issues'
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Assignee: ${{ github.event.issue.assignee.login }}"
          
      - name: Add issue to README
        if: github.event_name == 'issues'
        run: |
          echo "- ${{ github.event.issue.title }} - ${{ github.event.issue.assignee.login }}" >> README.md

      - name: Commit
        run: |
          git config user.name "tonipekkala24"
          git config user.email "tpekkala24@students.oamk.fi"
          git add README.md
          git commit -m "Add new issue to README"
          git push
          
      - name: Handle issue comment
        if: github.event_name == 'issue_comment'
        env:
          COMMENT: ${{ github.event.comment.body }}
          AUTHOR: ${{ github.event.comment.user.login }}
        run: |
          echo "Comment: $COMMENT"
          echo "Comment author: $AUTHOR"
